# reset the link of here library
```{r}
library(here)
current_here_location <- here()
print(current_here_location)

new_here_location <- "/Users/chenfen/Desktop/CASA/CASA0005 GIS"
set_here(new_here_location)
print(new_here_location)
# change the channel to library (here)
```
# 5.7.1 Spatial joining
```{r}
library(sf)
library(here)
library(dplyr)
#load the data and reproject it
Londonborough <- st_read(here::here("week5/week5data","London boroughs","statistical-gis-boundaries-london","ESRI","London_Borough_Excluding_MHW.shp"))%>%
  st_transform(.,27700)
```
```{r}
#load the data and reproject it
OSM <- st_read(here::here("week5/week5data",
                          "OSM",
                          "greater-london-latest-free.shp",
                          "gis_osm_pois_a_free_1.shp"))%>%
  st_transform(.,27700)
```
```{r}
#select hotels only
  OSM_hotel <- OSM %>%
  dplyr::filter(fclass == 'hotel')
```
```{r}
join_example <- st_join(Londonborough,OSM_hotel)
head(join_example)
#st_join() defaults to a left join
#so in this case the borough data is the left dataset and all the right data has been appended to it. 
#If the left data (borough) had no matches (so no hotels) they would still appear in the final dataset. 
```
#5.7.2 Static map
```{r}
library(sf)
library(tmap)
library(tmaptools)
library(tidyverse)
library(here)

Worldcities <- st_read(here::here("week5/week5data",
                                  "world cities",
                                  "World_Cities",
                                  "World_Cities.shp"))%>%
  st_transform(.,27700)

```
```{r}
UK_outline <- st_read(here::here("week5/week5data", 
                                 "UK outline", 
                                 "gadm41_GBR_shp",
                                 "gadm41_GBR_0.shp")) %>%
  st_transform(., 27700)
```
```{r}
# read in the .csv
# and make it into spatial data

# "st_as_sf"from the sf package in R to convert a data frame to a simple features (sf) object. 
Airbnb <- read_csv("/Users/chenfen/Desktop/CASA/CASA0005 GIS/CASA0005GIS_cqy/week5/week5data/airbnb/listings.csv")%>%
  st_as_sf(.,coords= c("longitude","latitude"),
           crs=4326)%>%
  st_transform(.,27700)%>%
   #select entire places that are available all year
    filter(room_type == 'Entire home/apt' & availability_365 =='365')
```

```{r}
# make a function for the join
Joinfun <- function(data1,data2){
  output <- data1%>%
    st_join(data2,.)%>%
    add_count(GSS_CODE,name="hotels_in_borough")%>%
    return(output)
  
}

#the add_count function is used to count the occurrences of each unique value in the GSS_CODE column.
#This column is assumed to be present in the result of the spatial join. The count information is added as a new column named "hotels_in_borough.

#the return() function is used to explicitly return a value from a function. 
#there are cases where it can be useful for clarity or in situations where you want to exit the function prematurely.
#在某些情况下，为了清晰起见，或者在想要提前退出函数的情况下，它可能是有用的。
```
```{r}
# use the function for hotels
Hotels <- Joinfun(OSM_hotel, Londonborough)

# then for airbnb
Airbnb <- Joinfun(Airbnb, Londonborough)
 
Worldcities2 <- Worldcities %>%
  filter(CNTRY_NAME=='United Kingdom'&
           Worldcities$CITY_NAME=='Birmingham'|
           Worldcities$CITY_NAME=='London'|
           Worldcities$CITY_NAME=='Edinburgh')

newbb <- c(xmin=-296000, ymin=5408, xmax=655696, ymax=1000000)
# create a vector named'newbb'in R, the min and max (y and x) coordinates of a bounding box.
UK_outlinecrop <- UK_outline$geometry %>%
  st_crop(., newbb)
#st_crop() is a function in the sf package in R, and it is used to crop or clip spatial geometries (points, lines, polygons, etc.) to a specified bounding box or geometry.
# st_crop(object,box)

#at the moment each hotel is a row for the borough
#we just one one row that has number of airbnbs: group_by in dplyr package, 
#grouped_data <- group_by(your_data, group_variable)
#to group data by the columns GSS_CODE and NAME
```
```{r}
Hotels <- Hotels %>%
  #at the moment each hotel is a row for the borough
  #we just one one row that has number of airbnbs
  group_by(., GSS_CODE, NAME)%>%
  summarise(`Accomodation count` = unique(hotels_in_borough))
#unique() is a function in R that is used to extract the unique elements from a vector. 
#to get the unique value of the variable hotels_in_borough within each group defined by GSS_CODE and NAME.
```
```{r}

Airbnb <- Airbnb %>%
  group_by(., GSS_CODE, NAME)%>%
  summarise(`Accomodation count` = unique(hotels_in_borough))
```
## Make the map
```{r}
tmap_mode("plot")
# set the breaks
# for our mapped data
breaks = c(0, 5, 12, 26, 57, 286) 

# plot each map
tm1 <- tm_shape(Hotels) +
  tm_polygons("Accomodation count",
              breaks= breaks,
              palette="PuBu") +
  tm_legend(show = FALSE) +
  tm_layout(frame = FALSE) +
  tm_credits("(a)", position = c(0,0.85),size = 1.5)
  
tm2 <- tm_shape(Airbnb) +
  tm_polygons("Accomodation count",
              breaks = breaks, palette="PuBu")  +
  tm_legend(show = FALSE) +
  tm_layout(frame = FALSE) +
  tm_credits("(b)", position = c(0,0.85),size = 1.5)

tm3 <- tm_shape(UK_outlinecrop)+ 
  tm_polygons(col="darkslategray1")+
  tm_layout(frame=FALSE)+
  tm_shape(Worldcities2) +
  tm_symbols(col = "red", scale = .5)+
  tm_text("CITY_NAME", xmod=-1, ymod=-0.5)
 
# xmod = -1 and ymod = -0.5: These parameters control the positioning of the text labels.
# They are modifiers for adjusting the position of the labels relative to their original position on the map. 

legend <- tm_shape(Hotels) +
    tm_polygons("Accomodation count",
                breaks=breaks,
                palette="PuBu") +
    tm_scale_bar(position=c(0.2,0.04), text.size=0.6)+
    tm_compass(north=0, position=c(0.65,0.6))+
    tm_layout(legend.only = TRUE, legend.position=c(0.2,0.25),asp=0.1)+
    tm_credits("(c) OpenStreetMap contrbutors and Airbnb", position=c(0.0,0.0))
  
t=tmap_arrange(tm1, tm2, tm3, legend, ncol=2)

t


#ncol = 2: This parameter specifies the number of columns in which the maps should be arranged. In this case, it's set to 2, meaning that the maps and the legend will be arranged in two columns.
#该参数指定了地图排列的列数。在本例中，它被设置为 2，这意味着地图和图例将排列成两列。
```
```{r}
library(grid)
#The grid package in R is part of the base graphics system and provides low-level functions for creating and manipulating grid graphics.
#working with grid-based graphics
#
grid.newpage()
pushViewport(viewport(layout = grid.layout(2,2)))
#print the different tmap objects in a 2*2 grid
print(tm1, vp=viewport(layout.pos.col=1, layout.pos.row=1, height=5))
# column 1 and row 1-(top-left)
#The height parameter in viewport is used to control the height of each plot within the grid.
print(tm2, vp=viewport(layout.pos.col=2, layout.pos.row=1, height=5))
# column 2 and row 1-(top-right)
print(tm3, vp=viewport(layout.pos.col=1, layout.pos.row=2, height=5))
# column 1 and row 2-(bottom-left)
print(legend, vp=viewport(layout.pos.col=2, layout.pos.row=2, height=5))
# column 2 and row 2-(bottom-right)
```
##5.7.3 Inset map
```{r}
# we need this to convert it into a class of sf
# otherwise it our bb won't have a class it will just be x and y coordinates for the box
# this makes it into a polygon

# Londonbb should be a polygon representing the bounding box of your original Airbnb spatial object.
Londonbb <- st_bbox(Airbnb,crs=st_crs(Airbnb))%>%
  st_as_sfc()
#The st_bbox function returns the bounding box (or extent) of a spatial object, and then st_as_sfc is used to convert this bounding box into a simple feature geometry.

#st_bbox(Airbnb, crs = st_crs(Airbnb)): Calculates the bounding box of the Airbnb spatial object. The crs argument ensures that the bounding box is in the same coordinate reference system (CRS) as the original spatial object.

#st_as_sfc(): Converts the bounding box into a simple feature geometry. This is important if you want to use the bounding box as a spatial object with sf functionality.
 plot(Londonbb)
```
```{r}
main <- tm_shape(Airbnb, bbbox = Londonbb) +
  tm_polygons("Accomodation count",
              breaks=breaks,
              palette="PuBu")+
  tm_scale_bar(position = c("left","bottom"), text.size = .75)+
  tm_layout(legend.position = c("right","top"),
            legend.text.size =.75,
            legend.title.size = 1.1,
            frame = FALSE)+
#frame = FALSE: This argument controls whether a frame (border) should be drawn around the legend. Setting it to FALSE means no frame will be drawn.
#frame = FALSE：该参数控制是否在图例周围绘制边框。设置为 FALSE 表示不绘制边框。
  tm_credits("(c) OpenStreetMap contrbutors and Air b n b",position = c(0,0,0) )+
  tm_compass(type = "8star", position=c(0.06,0.1)) +
  tm_layout(inner.margins = c(0.02,0.02,0.02,0.2))
#The argument inner.margins allows you to set the inner margins of the plot, controlling the space between the map elements and the plot edges.(内边距)

inset= tm_shape(UK_outlinecrop)+tm_polygons()+
  #add the polygons from the UK_outlinecrop spatial object to the map.
  tm_shape(Londonbb)+
  tm_borders(col = "grey40",lwd = 3)+
  #Adds the borders of the bounding box (Londonbb) to the map,Lwd(linewidth)
  tm_layout(frame = FALSE,
            bg.color = "transparent")+
  #Adjusts the layout settings
  #setting the background color to transparent (bg.color = "transparent").
  tm_shape(Worldcities2)+
  tm_symbols(col = "red",scale = 0.5)+
  #add symbols(points)fromthe spatial object to the map
  tm_text("CITY_NAME",xmod=-1.5,ymod = -0.5)
#Adds text labels to the map based on the "CITY_NAME" variable, adjusting their position with xmod and ymod.
```
```{r}
library(grid)
main
print(inset, vp = viewport(0.86, 0.29, width = 0.5, height = 0.55))
# viewport form grid package
# 0.86: X-coordinate of the left edge of the viewport (86% of the total width).视口左边缘的 X 坐标（总宽度的 86%）
# 0.29: Y-coordinate of the bottom edge of the viewport (29% of the total height).视口底部边缘的 Y 坐标（总高度的 29%）
# width = 0.5: Width of the viewport (50% of the total width).视口宽度（总宽度的 50%）
# height = 0.55: Height of the viewport (55% of the total height).视口高度（总高度的 55%）
```
##5.7.4 Export
```{r}
#Saving PNG image:
tmap_save(t,"hotelsandairbnbR.png")
#Saving a PDF File with Insets:
library(grid)
tmap_save(main,insets_tm = inset,insets_vp = viewport(x=0.86,y=0.29,width = .5,height = .55),filename = "insetmap.pdf",dpi = 600)
#!!!
```
##5.7.5 Basic interactive map
```{r}
tmap_mode("view")

Airbnb2 <- read_csv("week5/week5data/airbnb/listings.csv")%>%
  st_as_sf(.,coords= c("longitude","latitude"),
           crs=4326)%>%
  st_transform(.,27700)%>%
   #select entire places that are available all year
    filter(room_type == 'Entire home/apt' & availability_365 =='365')

Airbnb2 <- Joinfun(Airbnb2, Londonborough)

Airbnb2 <- Airbnb2 %>%
  group_by(., GSS_CODE, NAME)%>%
  summarise(`Accomodation count` = unique(hotels_in_borough))

tm_shape(Airbnb2) + 
  tm_polygons("Accomodation count",breaks=breaks)


```


```{r}
tm_shape(Hotels) + 
  tm_polygons("Accomodation count",breaks=breaks)
```
##5.7.6 Advanced interactive map
```{r}
install.packages("leafpop")
install.packages("leaflet")
```
```{r}
library(leafpop)
library(leaflet)
library(dplyr)
library(sf)
library(tmap)
library(tmaptools)
library(tidyverse)
library(here)
```


```{r}
#join data
Joined <- Airbnb%>%
  st_join(., Hotels, join = st_equals)%>%
  dplyr::select(GSS_CODE.x, NAME.x, `Accomodation count.x`, `Accomodation count.y`)%>%
  dplyr::rename(`GSS code` =`GSS_CODE.x`,
                `Borough` = `NAME.x`,
                `Airbnb count` = `Accomodation count.x`,
                `Hotel count`= `Accomodation count.y`)%>%
  st_transform(., 4326)
  
  
#remove the geometry for our pop up boxes to avoid
popupairbnb <-Joined %>%
  st_drop_geometry()%>%
  dplyr::select(`Airbnb count`, Borough)%>%
  popupTable()

popuphotel <-Joined %>%
  st_drop_geometry()%>%
  dplyr::select(`Hotel count`, Borough)%>%
  popupTable()

tmap_mode("view")

# set the colour palettes using our previously defined breaks


pal1 <- Joined %>%
  colorBin(palette = "YlOrRd", domain=.$`Airbnb count`, bins=breaks)

pal1 <-colorBin(palette = "YlOrRd", domain=Joined$`Airbnb count`, bins=breaks)

pal2 <- Joined %>%
  colorBin(palette = "YlOrRd", domain=.$`Hotel count`, bins=breaks)


map<- leaflet(Joined) %>%
  # add basemap options
  addTiles(group = "OSM (default)") %>%
  addProviderTiles(providers$Stamen.Toner, group = "Toner") %>%
  addProviderTiles(providers$Stamen.TonerLite, group = "Toner Lite") %>%
  addProviderTiles(providers$CartoDB.Positron, group = "CartoDB")%>%
  
  #add our polygons, linking to the tables we just made
  addPolygons(color="white", 
              weight = 2,
              opacity = 1,
              dashArray = "3",
              popup = popupairbnb,
              fillOpacity = 0.7,
              fillColor = ~pal2(`Airbnb count`),
              group = "Airbnb")%>%
  
  addPolygons(fillColor = ~pal2(`Hotel count`), 
              weight = 2,
              opacity = 1,
              color = "white",
              dashArray = "3",
              popup = popupairbnb,
              fillOpacity = 0.7,group = "Hotels")%>%
  # add a legend
  addLegend(pal = pal2, values = ~`Hotel count`, group = c("Airbnb","Hotel"), 
            position ="bottomleft", title = "Accomodation count") %>%
  # specify layers control
  addLayersControl(
    baseGroups = c("OSM (default)", "Toner", "Toner Lite", "CartoDB"),
    overlayGroups = c("Airbnb", "Hotels"),
    options = layersControlOptions(collapsed = FALSE)
  )
# plot the map
map

```
